package hr.fer.oop.lab3.implementation;

import hr.fer.oop.lab3.welcomepack.Constants;

/**
 * Abstract class that simulates a person, must be inherited.
 * 
 * @author Luka
 *
 */

public abstract class Person {
	private String name;
	private String country;
	private int emotion;
	
	/**
	 * Getter for name
	 * @return name
	 */
	
	public String getName() {
		return name;
	}
	
	/**
	 * Getter for country
	 * @return country
	 */

	public String getCountry() {
		return country;
	}
	
	/**
	 * Getter for emotion
	 * @return emotion
	 */
	
	public int getEmotion() {
		return emotion;
	}
	
	/**
	 * Setter for emotion
	 * @param emotion
	 */
	
	public void setEmotion(int emotion) {
		if(emotion>=0 && emotion<=100) {
			this.emotion=emotion;
		} else {
			this.emotion=Constants.DEFAULT_EMOTION;
			System.err.println("ERROR: emotion out of bounds");
		}
	}
	
	/**
	 * Constructor for default values
	 */
	
	public Person() {
		this.name=Constants.DEFAULT_PLAYER_NAME;
		this.country=Constants.DEFAULT_COUNTRY;
		this.emotion=Constants.DEFAULT_EMOTION;
	}
	
	/**
	 * Constructor
	 * @param name
	 * @param country
	 * @param emotion
	 */
	
	public Person(String name, String country, int emotion) {
		if(name!=null && !name.equals("")) {
			this.name=name;
		} else {
			this.name=Constants.DEFAULT_PLAYER_NAME;
			System.err.println("ERROR: invalid name");
		}
		if(country!=null && !country.equals("")) {
			this.country=country;
		} else {
			this.country=Constants.DEFAULT_COUNTRY;
			System.err.println("ERROR: invalid country");
		}
		if(emotion >=0 && emotion<=100) {
			this.emotion=emotion;
		} else {
			this.emotion=Constants.DEFAULT_EMOTION;
			System.err.println("ERROR: emotion out of bounds");
		}
	}
	
	/**
	 * Overrides hashCode(), automatically generated by Eclipse.
	 */
	
	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((country == null) ? 0 : country.hashCode());
		result = prime * result + ((name == null) ? 0 : name.hashCode());
		return result;
	}
	
	/**
	 * Overrides equals(), automatically generated by Eclipse.
	 */
	
	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}
		if (obj == null) {
			return false;
		}
		if (!(obj instanceof Person)) {
			return false;
		}
		Person other = (Person) obj;
		if (country == null) {
			if (other.country != null) {
				return false;
			}
		} else if (!country.equals(other.country)) {
			return false;
		}
		if (name == null) {
			if (other.name != null) {
				return false;
			}
		} else if (!name.equals(other.name)) {
			return false;
		}
		return true;
	}
}